import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { TrpcProvider } from "~/trpc/TrpcProvider";
import Link from "next/link";
import { getServerAuthSession } from "~/server/auth";
import { headers } from "next/headers";
import { redirect } from "next/navigation";
import { Toaster } from "./_components/ui/toaster";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const session = await getServerAuthSession();
  const headersList = headers();
  const url = headersList.get("x-url");

  if (!session && url && !url.includes("/login")) {
    if (url) {
      redirect(`/login?redirect=${encodeURIComponent(url)}`);
    }
    redirect("/login");
  }

  if (url && url.includes("/login")) {
    return <Base>{children}</Base>;
  }

  return (
    <Base>
      <div className="flex h-full flex-col gap-4 p-4">
        <header>
          <nav className="flex justify-between">
            <h1 className="text-4xl">Diary App</h1>
            <ul className="flex items-center gap-2">
              <li>
                <Link href="/">Home</Link>
              </li>
              <li>
                <Link href="/diaries">Diaries</Link>
              </li>
            </ul>
          </nav>
        </header>
        <div className="h-full min-h-0 flex-1">
          <TrpcProvider headers={headers()}>{children}</TrpcProvider>
        </div>
      </div>
      <Toaster />
    </Base>
  );
}

function Base({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en" style={{ colorScheme: "dark" }} className="dark h-full">
      <body className={`${inter.className} mx-auto h-full max-w-7xl`}>
        {children}
      </body>
    </html>
  );
}
