import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { TrpcProvider } from "./trpc/TrpcProvider";
import Link from "next/link";
import { getServerAuthSession } from "~/server/auth";
import { headers } from "next/headers";
import { redirect } from "next/navigation";
import { Button } from "./components/ui/button";
import { signIn } from "next-auth/react";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const session = await getServerAuthSession();
  const headersList = headers();
  const referer = headersList.get("referer");

  console.log({ referer, session });

  if (!session && referer && !referer.includes("/login")) {
    if (referer) {
      redirect(`/login?redirect=${encodeURIComponent(referer)}`);
    }
    redirect("/login");
  }

  if (referer && referer.includes("/login")) {
    return <Base>{children}</Base>;
  }

  return (
    <Base>
      <div className="flex h-full flex-col gap-4 p-4">
        <header>
          <nav className="flex justify-between">
            <h1 className="text-4xl">Diary App</h1>
            <ul className="flex items-center gap-2">
              <li>
                <Link href="/">Home</Link>
              </li>
              <li>
                <Link href="/diaries">Diaries</Link>
              </li>
            </ul>
          </nav>
        </header>
        <div className="flex-1">
          <TrpcProvider>{children}</TrpcProvider>
        </div>
      </div>
    </Base>
  );
}

function Base({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en" style={{ colorScheme: "dark" }} className="dark h-full">
      <body className={`${inter.className} h-full`}>{children}</body>
    </html>
  );
}
